### ISSUE TITLE
Consistent handler signature

### ISSUE THREAD

**Issue by eliasmalik** [FAC10/week-4-zapo#59]
One of [your handlers](https://github.com/FAC10/week-4-zapo/blob/master/src/handler.js#L36) has an inconsistent signature. This indicates that the logic required to respond to requests to that route is split between the handler and the router. Typically a router should only understand which functions to call based on the request object, but shouldn't be given any context about what those functions/handlers are doing.

**Comment by oliverjam** [comment]
Is this way of handling better @eliascodes?

**Comment by eliasmalik** [comment]
Yes
