### ISSUE TITLE
Verb blanks are coming up with wrong suggestions (adjective instead of a verb)

### ISSUE THREAD

**Issue by majakudlicka** [FAC10/week-4-zapo#62]

**Comment by oliverjam** [comment]
Can you give an example of this? I only see verbs for any letters in any verb field.

**Comment by pbywater** [comment]
The english language is odd AF I'm afraid. http://www.dictionary.com/browse/english?s=t - 'English' can even be a verb....

![screenshot-www dictionary com 2017-03-17 11-06-22](https://cloud.githubusercontent.com/assets/20152018/24040637/f158bb8c-0b01-11e7-984d-efed95c01d20.png)
![screenshot-www dictionary com 2017-03-17 11-05-58](https://cloud.githubusercontent.com/assets/20152018/24040641/f2fb2538-0b01-11e7-8329-852b951aab84.png)

**Comment by oliverjam** [comment]
I think this might be an issue with our word lists having lots of very obscure words in them.

Not much we can do about English being weird, sorry!
