### ISSUE TITLE
Arguably excessive modularization

### ISSUE THREAD

**Issue by akinsho** [FAC10/week-4-zapo#63]
I think that your modularisation makes your code more readable in many instances but is potentially pushed towards being a little fragmented for example the serveapi module which is 3 lines long and forces another dev to go looking for this function

**Comment by oliverjam** [comment]
Sorry we forgot to delete that file. If you check `handlers.js` you'll see that we don't actually import that module. We realised the same thing you did - no point importing a 3 line function.
