### ISSUE TITLE
Remove assets file

### ISSUE THREAD

**Issue by skibinska** [FAC10/week-4-zapo#67]
Your assests file has only img that is used in README. You can create an issue and attach an img to it, and then add it to your README `![img description](link-to-your-img-from-issue)`

**Comment by ZooeyMiller** [comment]
![architecture](https://cloud.githubusercontent.com/assets/21139983/24043359/32f9055e-0b0e-11e7-8978-f27b450fa5d4.png)
thx for the advice! doing just that here.

**Comment by ZooeyMiller** [comment]
fixed by #79
