### ISSUE TITLE
Sorry I got distracted...

### ISSUE THREAD

**Issue by emilyb7** [FAC10/week-4-zapo#70]
Hey guys, I wanted to review your code but I got distracted and now we're out of time.

Just wanted to say that I love the originality of your idea and that the design is really simple and clean! Great tabbing through the different input fields.

Nice work, I trust that the code is just as good 💛

**Comment by ZooeyMiller** [comment]
Thank you!!! :sparkles:

**Comment by pbywater** [comment]
:sparkles:
