### ISSUE TITLE
File structure

### ISSUE THREAD

**Issue by skibinska** [FAC10/week-4-zapo#71]
- I think that a good idea is to separate your backend and frontend tests by creating *frontend* and *backend* folders inside tests folder
-  *word-processing* folder should be in src folder
- src folder should be better organise e.g. all handlers in *handler* folder

**Comment by pbywater** [comment]
We were a little unsure about putting word processing in the src folder as this code was only used when we created the jsons and could now be deleted. We wanted to keep the code for future reference but thought it might be confusing to have it in the src folder!

**Comment by ZooeyMiller** [comment]
There was a mistake in the commit which fixed this so am re-opening
